version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - auth-service
    networks:
      - backend-network

  auth-service:
    build:
      context: ./auth-service
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 